# training from scratch using a single gpu, default configs in config.py file
exp_name: multi_gpu
datadir: /data/datasets/CAPS-MegaDepth-release-light  # replace with your data dir
n_iters: 40
save_interval: 20
